### ISSUE TITLE
Include a section that contains information about log configuration files

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-desktop-app.en#1]
Issue in ./help/troubleshoot.md

Due to a reproducible bug with **Enable debug mode** on Windows, the debug logging can't be enabled via command terminal. The log level can also be set through configuration files.
_a) "C:\Program Files\Adobe\Adobe Experience Manager Desktop\Adobe Experience Manager Desktop.exe.config"_
Go to the bottom of the config wherein you find the <log4net> tag. In the <root> of it, change the value to DEBUG for <level> tag.
![image](https://user-images.githubusercontent.com/59624839/79145340-77fb3000-7d8e-11ea-8f19-23573a96d93e.png)

_b) "C:\Program Files\Adobe\Adobe Experience Manager Desktop\javascript\logging.json"_
Open logging.json file and change all the "level" values from "info" to "debug" & save it.
![image](https://user-images.githubusercontent.com/59624839/79145459-b264cd00-7d8e-11ea-83fc-014ead3790e6.png)

Then, clear all the cached directories that can be found in the following location set in Preferences, just as follows:
![image](https://user-images.githubusercontent.com/59624839/79145591-e5a75c00-7d8e-11ea-9711-3f84bab70415.png)

After performing the above steps, restart AEM Desktop App.

[Logged by AEM Support]

**Comment by ashishguptaiitb** [comment]
Hey! Thanks for sharing this. I believe you want me to document this method as the documented method doesn't seem to work. Did I get it right?
I shall circle back with engineering as well.

**Comment by sukohli** [comment]
Yes, Ashish. You got it right. :)
The documented method doesn't work on Windows(at least, that's what I confirmed). We just need to have a workaround in the meanwhile the actual issue gets resolved. :)

**Comment by ashishguptaiitb** [comment]
Thanks for confirming @sukohli . I saw your queries on Slack about the same, I guess. Good that you have already shared a handy workaround.

**Comment by sukohli** [comment]
@ashishguptaiitb 
No problem at all !! :)
Thanks, again !! 👍

**Comment by bohnertchris** [comment]
CQDOC-15799

**Comment by ashishguptaiitb** [comment]
This is updated at https://docs.adobe.com/content/help/en/experience-manager-desktop-app/using/troubleshoot.html#troubleshooting-prep
I'm closing this ticket. Thanks for sharing the method.
