### ISSUE TITLE
Login URL should have example, http://localhost:4502/

### ISSUE THREAD

**Issue by mattlaun** [AdobeDocs/experience-manager-desktop-app.en#10]
Issue in ./help/using.md

Found that if user enters http://localhost:4502/assets.html/content/dam
There is an initial view of the folder's contents, then they disappear and general error is shown... "The application encountered an unknown error." Doc should clearly indicate use of the server:port only.

**Comment by bohnertchris** [comment]
Thank you, @mattlaun, for the suggestion. We will look into it.

CQDOC-16618

**Comment by mgulati1** [comment]
Thanks @mattlaun. Fixed the doc issue through https://jira.corp.adobe.com/browse/CQDOC-16618.
