### ISSUE TITLE
Link to download Mac Desktop app sometimes fails

### ISSUE THREAD

**Issue by mattlaun** [AdobeDocs/experience-manager-desktop-app.en#11]
Issue in ./help/release-notes.md
I've had this work then not. Think it has something to do with the current state of SSO login?

**Comment by aheim0** [comment]
Thanks for raising this. As it is a platform issue we will have to pass this on to the appropriate team.

**Comment by aheim0** [comment]
@mattlaun 
I have just tried to access one of the links and am getting:

"Error 408: Request timeout
This page was not able to load. Try refreshing or visit a different page.
If you continue to get this message, contact customer care and reference:
EIM Instance Id de77f2f2-45a7-11eb-9849-e7e6b012f384"

I will pass this issue on, but it might be quicker if you contact support directl.y

**Comment by aheim0** [comment]
As this is not a documentation issue am closing this.

**Comment by aheim0** [comment]
Tracked with CUSC-2222.
