### ISSUE TITLE
Access to desktop app download leads to 404

### ISSUE THREAD

**Issue by daronson1** [AdobeDocs/experience-manager-desktop-app.en#12]
Issue in ./help/release-notes.md

It is currently not possible to download any of the options for the Adobe Experience Manager Desktop App
These pages lead to 404s

- https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=/content/software-distribution/en/details.html/content/dam/aem/public/adobe/packages/adobe/aem-desktop-app/aem-desktop-osx-2.1.0.0.dmg
-https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=/content/software-distribution/en/details.html/content/dam/aem/public/adobe/packages/adobe/aem-desktop-app/aem-desktop-win64-2.1.0.0.exe
- https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=/content/software-distribution/en/details.html/content/dam/aem/public/adobe/packages/adobe/aem-desktop-app/aem-desktop-win32-2.1.0.0.exe

please address quickly

thanks,

Daniel

**Comment by aheim0** [comment]
Thank you for highlighting this - we will investigate.

**Comment by aheim0** [comment]
@daronson1 

Can we ask you to try the links again?

I have just tried - and all 3 worked successfully.

**Comment by aheim0** [comment]
Tracked with CQDOC-17328

**Comment by daronson1** [comment]
Hi @aheim0 - I have tried with normal browser, and incongnito, and still get the 404 when I sign into the experience cloud...

I do not appear to have access to the files

**Comment by aheim0** [comment]
@daronson1 

Can you access the Software Distribution site at all? 

At the link:

- https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html

Thanks for checking.

**Comment by daronson1** [comment]
@aheim0 - no, that also returns a 404

**Comment by aheim0** [comment]
@daronson1 

I have just tried that last link on a completely different computer - and I can successfully access the Software Distribution site.

As this is not an actual documentation issue I'll have to ask you to contact Adobe Support. I hope they can help you further.
