### ISSUE TITLE
Verify info about special characters handling

### ISSUE THREAD

**Issue by ashishguptaiitb** [AdobeDocs/experience-manager-desktop-app.en#15]
Issue in ./help/using.md

In the section 'Manage special characters in asset names', verify the info in the first row of the table. It doesn't seem correct. Thanks.

**Comment by anujkapo** [comment]
Thanks, @ashishguptaiitb. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by sarasp32** [comment]
Hi @ashishguptaiitb , The page has been updated. Here's the [live link](https://experienceleague.adobe.com/docs/experience-manager-desktop-app/using/using.html) to the same.
