### ISSUE TITLE
PDF link in DA docs is not rendering as a link

### ISSUE THREAD

**Issue by ashishguptaiitb** [AdobeDocs/experience-manager-desktop-app.en#19]
PDF destination: https://experienceleague.adobe.com/docs/experience-manager-desktop-app/assets/aem_desktop_app_usecases_print.pdf

Help article: https://experienceleague.adobe.com/docs/experience-manager-desktop-app/using/using.html

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bbringhu** [comment]
You need to add an extra hard return between the paragraphs.

```
The key tasks you perform using the [!DNL Adobe Experience Manager] desktop app are:

![Workflows and tasks you can accomplish using [!DNL Experience Manager] desktop app](assets/aem_desktop_app_usecases_v2.png "Workflows and tasks you can accomplish using [!DNL Adobe Experience Manager] desktop app")

Download [this](assets/aem_desktop_app_usecases_print.pdf) print-ready PDF file.
```

**Comment by bbringhu** [comment]
Fixed

**Comment by aheim0** [comment]
@ashishguptaiitb 
Thanks for raising this. Changes have been made and published.
