### ISSUE TITLE
Need SAML troubleshooting section for Desktop App version 2

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-desktop-app.en#2]
Issue in ./help/troubleshoot.md

Need SAML troubleshooting section for Desktop App version 2.
If customers have SAML login authentication setup and it's not working they need help in the diagnosis.
There is some SAML discussion for version 1, but is it different for version 2?

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @johnb4. We will look into this.

CQDOC-16145

**Comment by mgulati1** [comment]
@johnb4 I have updated the docs. Kindly let me know if there are any issues.

**Comment by mgulati1** [comment]
https://docs.adobe.com/content/help/en/experience-manager-desktop-app/using/troubleshoot.html
