### ISSUE TITLE
Need whole troubleshooting section about connection issues

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-desktop-app.en#3]
Issue in ./help/troubleshoot.md

Connecting via Desktop 2 to AEM needs it's own troubleshooting section.
Possible discussion points:
1. Using regular AEM login
2. Using SAML
3. When you would use the "Use a different URL for the login page (advanced)"
4. What to monitor on client and server side (as in what logs to look into)

**Comment by mgulati1** [comment]
@johnb4  Updated the troubleshooting article for version2 and pushed the changes live https://docs.adobe.com/content/help/en/experience-manager-desktop-app/using/troubleshoot.html.
