### ISSUE TITLE
Step 1 of instructions includes instruction to save when nothing is changed yet

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-desktop-app.en#4]
Issue in ./help/troubleshoot.md

Why does step 1 of the "Enable debug mode" for Windows say "Save and close the file." when we have not changed anything yet?

**Comment by bohnertchris** [comment]
Thank you for reporting, @johnb4. We will have a look.

CQDOC-16187

**Comment by mgulati1** [comment]
Thanks @johnb4. The issue has been fixed and the updates are live at https://docs.adobe.com/content/help/en/experience-manager-desktop-app/using/troubleshoot.html. Closing the ticket. If there is any other issue kindly log a new ticket.
