### ISSUE TITLE
Step 4 of "Enable debug mode" references items that do not exist

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-desktop-app.en#5]
Issue in ./help/troubleshoot.md

Step 4 of "Enable debug mode" references a "level" parameter which does not exist.
If it does not exist then the documentation should show what it should look like so that it can be added.

Also, step 5 "Clear the cached directories that at the location set in the app preferences." is not proper English.

**Comment by bohnertchris** [comment]
Thank you for reporting, @johnb4. We will have a look.

CQDOC-16188

**Comment by mgulati1** [comment]
The changes are live at https://docs.adobe.com/content/help/en/experience-manager-desktop-app/using/troubleshoot.html. Closing the ticket. Kindly log a new ticket if any concerns are there.
