### ISSUE TITLE
System requirements for Mac OS X need to be updated

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-desktop-app.en#6]
Issue in ./help/release-notes.md

System requirements for Mac OS X need to be updated.  Please refer to internal JIRA CQ-4295259. 

[Logged by Support]

**Comment by bohnertchris** [comment]
Thank you for bringing this to our attention, @ycastane. We will review.

CQDOC-16240

**Comment by ashishguptaiitb** [comment]
The specs are updated @ycastane . I'm closing this ticket.

PS: You are in the loop in Jira about Window support update.
