### ISSUE TITLE
Desktop App compatibilty package

### ISSUE THREAD

**Issue by manish112** [AdobeDocs/experience-manager-desktop-app.en#8]
Issue in ./help/release-notes.md

The link mentioned on this doc for Compatibility package is https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq640/featurepack/adobe-asset-link-support

while the new URL is 

https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=/content/software-distribution/en/details.html/content/dam/aem/public/adobe/packages/cq640/featurepack/adobe-asset-link-support

Please update the docs.

**Comment by aheim0** [comment]
@manish112 Thanks for highlighting this, we will investigate.

**Comment by mgulati1** [comment]
Thanks @manish112. The issue was fixed through the commit (https://github.com/AdobeDocs/experience-manager-desktop-app.en/commit/c645ac48c832787733c183e4512350e6d9a78d33) you made on the branch Patch 1.
